### ISSUE TITLE
builds for OSX for version 10.10

### ISSUE THREAD

**Issue by i-n-g-o** [igrr/esptool-ck#19]
hi.

i just ran into the `esptool returned 139`-error on a 10.7.5 machine.

the release-builds for OSX are for system version min. 10.10.

```
...
  version 10.10
      sdk 10.10
```

 that creates problems on older systems.

**Comment by igrr** [comment]
Thanks, should be fixed by 36e2fd9.

**Comment by gmglickman** [comment]
Still a problem with my 10.7.5

esp8266/tools/esptool/0.4.6/esptool returned 139

**Comment by gmglickman** [comment]
Fixed by making new esptool using makefile, then installing to /Users/$USER/Library/Arduino15/packages/esp8266/tools/esptool/0.4.6/
